#ifndef CDPLAYER_INTERFACE_DEF_H
#define CDPLAYER_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.1.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_CDPLAYER_H
#include <libraries/cdplayer.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct CDPlayerIFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct CDPlayerIFace *Self);
	uint32 APICALL (*Release)(struct CDPlayerIFace *Self);
	void APICALL (*Expunge)(struct CDPlayerIFace *Self);
	struct Interface * APICALL (*Clone)(struct CDPlayerIFace *Self);
	BYTE APICALL (*CDEject)(struct CDPlayerIFace *Self, struct IOStdReq * io_ptr);
	BYTE APICALL (*CDPlay)(struct CDPlayerIFace *Self, UBYTE starttrack, UBYTE endtrack, struct IOStdReq * io_ptr);
	BYTE APICALL (*CDResume)(struct CDPlayerIFace *Self, BOOL mode, struct IOStdReq * io_ptr);
	BYTE APICALL (*CDStop)(struct CDPlayerIFace *Self, struct IOStdReq * io_ptr);
	BYTE APICALL (*CDJump)(struct CDPlayerIFace *Self, LONG blocks, struct IOStdReq * io_ptr);
	BOOL APICALL (*CDActive)(struct CDPlayerIFace *Self, struct IOStdReq * io_ptr);
	ULONG APICALL (*CDCurrentTitle)(struct CDPlayerIFace *Self, struct IOStdReq * io_ptr);
	BYTE APICALL (*CDTitleTime)(struct CDPlayerIFace *Self, struct CD_Time * cd_time, struct IOStdReq * io_ptr);
	BYTE APICALL (*CDGetVolume)(struct CDPlayerIFace *Self, struct CD_Volume * vol, struct IOStdReq * io_ptr);
	BYTE APICALL (*CDSetVolume)(struct CDPlayerIFace *Self, const struct CD_Volume * vol, struct IOStdReq * io_ptr);
	BYTE APICALL (*CDReadTOC)(struct CDPlayerIFace *Self, struct CD_TOC * toc, struct IOStdReq * io_ptr);
	BYTE APICALL (*CDInfo)(struct CDPlayerIFace *Self, struct CD_Info * cdi, struct IOStdReq * io_ptr);
	BYTE APICALL (*CDPlayAddr)(struct CDPlayerIFace *Self, ULONG startaddr, ULONG endaddr, struct IOStdReq * io_ptr);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* CDPLAYER_INTERFACE_DEF_H */
