#ifndef INLINE4_CDPLAYER_H
#define INLINE4_CDPLAYER_H

/*
** This file was auto generated by idltool 53.1.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_CDPLAYER_H
#include <libraries/cdplayer.h>
#endif
#include <interfaces/cdplayer.h>

/* Inline macros for Interface "main" */
#define CDEject(io_ptr) ICDPlayer->CDEject((io_ptr)) 
#define CDPlay(starttrack, endtrack, io_ptr) ICDPlayer->CDPlay((starttrack), (endtrack), (io_ptr)) 
#define CDResume(mode, io_ptr) ICDPlayer->CDResume((mode), (io_ptr)) 
#define CDStop(io_ptr) ICDPlayer->CDStop((io_ptr)) 
#define CDJump(blocks, io_ptr) ICDPlayer->CDJump((blocks), (io_ptr)) 
#define CDActive(io_ptr) ICDPlayer->CDActive((io_ptr)) 
#define CDCurrentTitle(io_ptr) ICDPlayer->CDCurrentTitle((io_ptr)) 
#define CDTitleTime(cd_time, io_ptr) ICDPlayer->CDTitleTime((cd_time), (io_ptr)) 
#define CDGetVolume(vol, io_ptr) ICDPlayer->CDGetVolume((vol), (io_ptr)) 
#define CDSetVolume(vol, io_ptr) ICDPlayer->CDSetVolume((vol), (io_ptr)) 
#define CDReadTOC(toc, io_ptr) ICDPlayer->CDReadTOC((toc), (io_ptr)) 
#define CDInfo(cdi, io_ptr) ICDPlayer->CDInfo((cdi), (io_ptr)) 
#define CDPlayAddr(startaddr, endaddr, io_ptr) ICDPlayer->CDPlayAddr((startaddr), (endaddr), (io_ptr)) 

#endif /* INLINE4_CDPLAYER_H */
